version: '3.9'

services:
  api:
    container_name: notes_api
    build:
      context: .
      dockerfile: NotesApp-Back/NotesApp.WebApi/Dockerfile
    ports:
      - "5134:5134"
      - "7241:7241"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NotesAppDDb;User=sa;Password=Admin@1234;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - app-network
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: notes_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@1234
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data: